<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>netstandard2.1</TargetFramework><AssemblyName>TimberUi</AssemblyName><RootNamespace>TimberUi</RootNamespace><LangVersion>latest</LangVersion></PropertyGroup><ItemGroup><ProjectReference Include="../Bindito.Core/Bindito.Core.Stub.csproj" Private="false"/><ProjectReference Include="../UnityEngine.UIElementsModule/UnityEngine.UIElementsModule.Stub.csproj" Private="false"/></ItemGroup></Project>