<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="../Targets/CommonProperties.targets" />
	
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<!--<ProjectReference Include="..\TimberUi\TimberUi\TimberUi.csproj" />-->
		<!--<ProjectReference Include="..\ModdableTimberborn\ModdableTimberborn.csproj" />-->

		<ProjectReference Include="..\ScienceShop\ScienceShop.csproj" />
		
	</ItemGroup>
</Project>
