<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>BenchmarkAndOptimizerV11</AssemblyName>
    <RootNamespace>BenchmarkAndOptimizerV11</RootNamespace>
    <AssemblyVersion>1.1.0.0</AssemblyVersion>
    <FileVersion>1.1.0.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="References/**/*.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Lib.Harmony" Version="2.4.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <ProjectReference Include="References/Timberborn.Modding.Stub.csproj" Private="false" />
  </ItemGroup>
</Project>
