<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>netstandard2.1</TargetFramework><AssemblyName>ModSettings.CoreUI</AssemblyName><RootNamespace>ModSettings.CoreUI</RootNamespace></PropertyGroup><ItemGroup><ProjectReference Include="../ModSettings.Core/ModSettings.Core.Stub.csproj" Private="false"/><ProjectReference Include="../UnityEngine.UIElementsModule/UnityEngine.UIElementsModule.Stub.csproj" Private="false"/></ItemGroup></Project>