<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="../Targets/CommonTests.targets" />
	<Import Project="../Targets/Common.targets" />
	<Import Project="../Targets/CommonTimberUi.targets" />

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<Compile Include="..\ModdableTimberborn.Tests\GameAssemblyFixture.cs" Link="GameAssemblyFixture.cs" />
		<Content Include="..\ModdableTimberborn.Tests\xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>

	<ItemGroup>
		<AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
			<_Parameter1>AssemblyProbePath</_Parameter1>
			<_Parameter2>$(GameModsFolder)TimberUi\$(TimberbornVersion)</_Parameter2>
		</AssemblyAttribute>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
		<PackageReference Include="xunit.v3" Version="3.0.1" />
		<PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\GlobalInventory\GlobalInventory.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="Xunit" />
		<Using Include="GlobalInventory.Services" />
		<Using Include="GlobalInventory.Specs" />
	</ItemGroup>

</Project>
