<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>netstandard2.1</TargetFramework><AssemblyName>ModSettings.Core</AssemblyName><RootNamespace>ModSettings.Core</RootNamespace></PropertyGroup><ItemGroup><ProjectReference Include="../Timberborn.Modding/Timberborn.Modding.Stub.csproj" Private="false"/><ProjectReference Include="../Timberborn.SettingsSystem/Timberborn.SettingsSystem.Stub.csproj" Private="false"/></ItemGroup></Project>